version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: tienda_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tienda_db
      MYSQL_USER: proy2
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
      - ./db/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uproy2", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: tienda_backend
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: tienda_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data: